/*Question: Input type String. Output type number. Print out the maximum even number which can be generated by 
making combinations of numbers present in the given string. Each number can be used only once i.e. 
No Redundancy.

SAMPLE TEST CASE 1:
Input String = Infytq@218412
Intermediate step (List of numbers //redundancy removed) = [2,1,8,4]
Output Number = 8412*/

import java.util.*;
class GenEven{
    public static void main(String[] args) {
        Scanner s =new Scanner(System.in);
        String str=s.nextLine();
        str=str.replaceAll("[^0-9]","");
        System.out.println(str.length());
        Set<Integer> numb=new HashSet<Integer>();
        for(int i=0;i<str.length();i++){
            numb.add(Integer.parseInt(String.valueOf(str.charAt(i))));
        }
        //System.out.println(numb.toString());
        int fin=0,len2=numb.size();
        for(int i=0;i<len2;i++){
            int min=Collections.min(numb);
            //System.out.println(max);
            fin=((min*(int)Math.pow(10,i))+fin);
            //System.out.println(fin);
            numb.remove(min);
            //System.out.println(numb.toString());
        }
        System.out.println(fin);
    }
}
